FitnessGuru/Models/WorkoutLog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FitnessGuru.Models
{
    public class WorkoutLog
    {
        public int Id { get; set; }
        public Guid UserId { get; set; }
        [Required]
        [Display(Name = "Name of Workout")]
        public int WorkoutId { get; set; }
        [ForeignKey("WorkoutId")]
        public virtual WorkoutModel Workout { get; set; }
        [Required]
        [Display(Name = "For how long?")]
        public float TimePeriod { get; set; }
        public double Calorie { get; set; }
        public DateTime TimeStamp { get; set; }
    }
}

FitnessGuru/Controllers/WorkoutLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessGuru.Models;
using Microsoft.AspNet.Identity;

namespace FitnessGuru.Controllers
{
    public class WorkoutLogsController : Controller
    {
        private FitnessDbCM db = new FitnessDbCM();

        // GET: WorkoutLogs
        public ActionResult Index()
        {
            DateTime Time = DateTime.Now.Date;
            var workoutLogs = db.WorkoutLogs.Where(p => p.TimeStamp == Time).Include(w => w.Workout);

            return View(workoutLogs.ToList());
        }

        // GET: WorkoutLogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutLog workoutLog = db.WorkoutLogs.Find(id);
            if (workoutLog == null)
            {
                return HttpNotFound();
            }
            return View(workoutLog);
        }

        // GET: WorkoutLogs/Create
        public ActionResult Create()
        {
            WorkoutLog model = new WorkoutLog() { UserId = GetCurrentUserId() };
            ViewBag.WorkoutId = new SelectList(db.Workouts, "Id", "WorkoutName");
            return PartialView(model);
        }

        // POST: WorkoutLogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,WorkoutId,TimePeriod,Calorie,TimeStamp")] WorkoutLog workoutLog)
        {
            if (ModelState.IsValid)
            {
                workoutLog.UserId = GetCurrentUserId();
                workoutLog.Calorie = GetCalorie(workoutLog);
                workoutLog.TimeStamp = DateTime.Now;
                db.WorkoutLogs.Add(workoutLog);
                db.SaveChanges();
                return RedirectToAction("RemainingCalWorkout", "RemainingCalories", workoutLog);
            }
            ViewBag.UserId = GetCurrentUserId();
            ViewBag.WorkoutId = new SelectList(db.Workouts, "Id", "WorkoutName", workoutLog.WorkoutId);
            return View(workoutLog);
        }

        // GET: WorkoutLogs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    WorkoutLog workoutLog = db.WorkoutLogs.Find(id);
        //    if (workoutLog == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.WorkoutId = new SelectList(db.Workouts, "Id", "WorkoutName", workoutLog.WorkoutId);
        //    return View(workoutLog);
        //}

        //// POST: WorkoutLogs/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,UserId,WorkoutId,TimePeriod,Calorie,TimeStamp")] WorkoutLog workoutLog)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(workoutLog).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.WorkoutId = new SelectList(db.Workouts, "Id", "WorkoutName", workoutLog.WorkoutId);
        //    return View(workoutLog);
        //}

        // GET: WorkoutLogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorkoutLog workoutLog = db.WorkoutLogs.Find(id);
            if (workoutLog == null)
            {
                return HttpNotFound();
            }
            return View(workoutLog);
        }

        // POST: WorkoutLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WorkoutLog workoutLog = db.WorkoutLogs.Find(id);
            db.WorkoutLogs.Remove(workoutLog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public Guid GetCurrentUserId()
        { //to allow user to view only their details
            return new Guid(User.Identity.GetUserId());
        }
        public bool EnsureIsUserContact(UserInfo userInfo)
        {
            return userInfo.UserId == GetCurrentUserId();
        }
        public float GetCalorie(WorkoutLog workoutLog)
        {
            var workout = db.Workouts.Find(workoutLog.WorkoutId);

            float calorie = workoutLog.TimePeriod * workout.Calories;
            return calorie;
        }
    }
}

FitnessGuru/Views/WorkoutLogs/Create.cshtml
@model FitnessGuru.Models.WorkoutLog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "WorkoutLogs", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkoutLog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           
            <div class="col-md-10">
               @Html.HiddenFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkoutId, "WorkoutId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WorkoutId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkoutId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimePeriod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimePeriod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimePeriod, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD" class="btn btn-default" />
            </div>
        </div>
    </div>
}

FitnessGuru/Views/WorkoutLogs/Delete.cshtml
@model FitnessGuru.Models.WorkoutLog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkoutLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Workout.WorkoutName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Workout.WorkoutName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimePeriod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimePeriod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FitnessGuru/Views/WorkoutLogs/Details.cshtml
@model FitnessGuru.Models.WorkoutLog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>WorkoutLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Workout.WorkoutName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Workout.WorkoutName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimePeriod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimePeriod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeStamp)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FitnessGuru/Views/WorkoutLogs/Edit.cshtml
@model FitnessGuru.Models.WorkoutLog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WorkoutLog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkoutId, "WorkoutId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("WorkoutId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WorkoutId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimePeriod, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimePeriod, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimePeriod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeStamp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TimeStamp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TimeStamp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FitnessGuru/Views/WorkoutLogs/Index.cshtml
@model IEnumerable<FitnessGuru.Models.WorkoutLog>

@{
    ViewBag.Title = "Workout You did Today!!";
}

<h2>ViewBag.Title = "Workout You did Today!!"</h2>

    ADD A Workout
<button type="button" class="btn btn" id="addWorkout"> <i class="fa fa-plus fa-spin fa-lg fa-fw" aria-hidden="true"></i></button>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Workout.WorkoutName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimePeriod)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Calorie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeStamp)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Workout.WorkoutName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimePeriod)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Calorie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TimeStamp)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

@section Scripts {
    <script>

        $("#addWorkout").on('click', function () {

            $.ajax({
                url: '/WorkoutLogs/Create',
                type: 'get'
            }).done(function (data) {
                $("#modalBody").html(data);
                $("#myModalLabel").html("Add Food");
                $("#myModal").modal("show");
            }).fail(function (err) {
                alert(err);
            });

        });

    </script>
}