FitnessGuru/Controllers/UserInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessGuru.Models;
using Microsoft.AspNet.Identity;

namespace FitnessGuru.Controllers
{
    [Authorize]
    public class UserInfoesController : Controller
    {
        private FitnessDbCM db = new FitnessDbCM();

        // GET: UserInfoes
        public ActionResult Index()
        {
            var userId = GetCurrentUserId();
            return View(db.Users.Where(x=>x.UserId== userId).ToList());
        }

        // GET: UserInfoes/Details/5
        public ActionResult Details()
        {
            var userid = GetCurrentUserId();
            UserInfo userInfo = db.Users.Where(p=>p.UserId == userid).FirstOrDefault();

            if (userInfo == null || !EnsureIsUserContact(userInfo))
            {
                return HttpNotFound();
            }
            return View(userInfo);
        }

        // GET: UserInfoes/Create
        public ActionResult Create()
        {
            ViewBag.UserId = GetCurrentUserId();
            var vm = new UserInfo();
            // Hard coded for demo. You can replace with real data from db
            vm.Activeness = new List<SelectListItem> {
                new SelectListItem { Value ="1", Text="Sedentary" },
                new SelectListItem { Value ="2", Text="Lightly Active" },
                new SelectListItem { Value ="3", Text="Moderately Active" },
                new SelectListItem { Value ="4", Text="Very Active" },
                new SelectListItem { Value ="5", Text="Extremely Active" }
                  };
            vm.ActivenessId = 1;

            return View(vm);
        }

        // POST: UserInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,FName,LName,Address,PhoneNumber,RegisteredDate,Gender,Birthday,Age,Height,CurrentWt,Goalwt,ActivenessId")] UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                userInfo.UserId = GetCurrentUserId();
                userInfo.RegisteredDate = DateTime.Now;
                userInfo.Age = GetAge(userInfo);
                db.Users.Add(userInfo);
                db.SaveChanges();
                return RedirectToAction("Calculate","Calculations", userInfo);
            }
            ViewBag.UserId = GetCurrentUserId();
            userInfo.Activeness = new List<SelectListItem> {
                new SelectListItem { Value ="1", Text="Sedentary" },
                new SelectListItem { Value ="2", Text="Lightly Active" },
                new SelectListItem { Value ="3", Text="Moderately Active" },
                new SelectListItem { Value ="4", Text="Very Active" },
                new SelectListItem { Value ="5", Text="Extremely Active" }
                  };
            userInfo.ActivenessId = 1;
            return View(userInfo);
        }

        // GET: UserInfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userInfo = db.Users.Find(id);
            if (userInfo == null || !EnsureIsUserContact(userInfo))
            {
                return HttpNotFound();
            }
            userInfo.Activeness = new List<SelectListItem> {
                new SelectListItem { Value ="1", Text="Sedentary" },
                new SelectListItem { Value ="2", Text="Lightly Active" },
                new SelectListItem { Value ="3", Text="Moderately Active" },
                new SelectListItem { Value ="4", Text="Very Active" },
                new SelectListItem { Value ="5", Text="Extremely Active" }
                  };
            userInfo.ActivenessId = 1;

            return View(userInfo);
        }

        // POST: UserInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,FName,LName,Address,PhoneNumber,RegisteredDate,Gender,Birthday,Age,Height,CurrentWt,Goalwt,ActivenessId")] UserInfo userInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userInfo).State = EntityState.Modified;
                userInfo.UserId = GetCurrentUserId();
                    
                userInfo.Age = GetAge(userInfo);
                db.SaveChanges();
                return RedirectToAction("Calculate", "Calculations", userInfo);
            }
            userInfo.Activeness = new List<SelectListItem> {
                new SelectListItem { Value ="1", Text="Sedentary" },
                new SelectListItem { Value ="2", Text="Lightly Active" },
                new SelectListItem { Value ="3", Text="Moderately Active" },
                new SelectListItem { Value ="4", Text="Very Active" },
                new SelectListItem { Value ="5", Text="Extremely Active" }
                  };
            userInfo.ActivenessId = 1;
            ViewBag.UserId = GetCurrentUserId();
            return View(userInfo);
        }

        // GET: UserInfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserInfo userInfo = db.Users.Find(id);
            if (userInfo == null || !EnsureIsUserContact(userInfo))
            {
                return HttpNotFound();
            }
            return View(userInfo);
        }

        // POST: UserInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserInfo userInfo = db.Users.Find(id);
            if (!EnsureIsUserContact(userInfo))
            {
                return HttpNotFound();
            }
            db.Users.Remove(userInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public Guid GetCurrentUserId()
        { //to allow user to view only their details
            return new Guid(User.Identity.GetUserId());
        }
        public bool EnsureIsUserContact(UserInfo userInfo)
        {
            return userInfo.UserId == GetCurrentUserId();
        }
        public int GetAge(UserInfo userInfo)
        {
            // Save today's date.
            var today = DateTime.Today;
            // Calculate the age.
            var age = today.Year - userInfo.Birthday.Year;
            // Go back to the year the person was born in case of a leap year
            if (userInfo.Birthday > today.AddYears(-age)) age--;
            return age;
        }

        public ActionResult showInfo()
        {
            var userId = GetCurrentUserId();
            var userInfo = db.Users.Where(p => p.UserId == userId).FirstOrDefault();
            return PartialView(userInfo);
        }

    }
}

FitnessGuru/Views/UserInfoes/Create.cshtml
@model FitnessGuru.Models.UserInfo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@using (Html.BeginForm("Create", "UserInfoes", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId, new { id = "UserId", value = ViewBag.UserId })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control needsDatePicker" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentWt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentWt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentWt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goalwt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goalwt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goalwt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActivenessId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ActivenessId, Model.Activeness, "Select one")
                @Html.ValidationMessageFor(model => model.ActivenessId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    <script type="text/javascript">
        $(function () {
            $(".needsDatePicker").datepicker({
                dateFormat: "mm/dd/yy"
            });
            $(window).on('load', function () {

                $ajax({
                    url: '/UserInfoes/Create',
                    type: 'get'
                }).done(function (data) {
                    $('#modalBody').html(data);
                    $('#myModalLabel').html('Add Info')
                    $('#myModal').modal('show');
                }).fail(function (err) {
                    alert(err);
                });

            })

        });

    </script>

}

FitnessGuru/Views/UserInfoes/Delete.cshtml
@model FitnessGuru.Models.UserInfo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentWt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goalwt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goalwt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivenessId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivenessId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FitnessGuru/Views/UserInfoes/Details.cshtml
@model FitnessGuru.Models.UserInfo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisteredDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisteredDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Birthday)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthday)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentWt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goalwt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goalwt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActivenessId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActivenessId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FitnessGuru/Views/UserInfoes/Edit.cshtml
@model FitnessGuru.Models.UserInfo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId, new { id = "UserId", value = ViewBag.UserId })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.RegisteredDate, new { id = "RegisteredDate", value = ViewBag.RegisteredDate })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control  needsDatePicker" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CurrentWt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentWt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentWt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Goalwt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Goalwt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Goalwt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActivenessId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ActivenessId, Model.Activeness, "Select one")
                @Html.ValidationMessageFor(model => model.ActivenessId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    <script type="text/javascript">
            $(function(){
                $(".needsDatePicker").datepicker({
                    dateFormat: "mm/dd/yy"
                } );

            });

    </script>

}

FitnessGuru/Views/UserInfoes/Index.cshtml
@model IEnumerable<FitnessGuru.Models.UserInfo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RegisteredDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Birthday)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Height)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentWt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Goalwt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ActivenessId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RegisteredDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Birthday)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Height)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentWt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Goalwt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ActivenessId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

FitnessGuru/Views/UserInfoes/showInfo.cshtml
@model FitnessGuru.Models.UserInfo


<div>
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LName)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurrentWt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurrentWt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Goalwt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Goalwt)
        </dd>

    </dl>
    <a href="@Url.Action("Edit", null, new { id=Model.Id, area = string.Empty, controller = "UserInfoes"}, Request.Url.Scheme)" class="hvr-buzz-out">Edit</a>
</div>



@*<div>
        <h4>UserInfo</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.FName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.LName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LName)
            </dd>


            <dt>
                @Html.DisplayNameFor(model => model.Gender)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Gender)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Age)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Age)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Height)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Height)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CurrentWt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CurrentWt)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Goalwt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Goalwt)
            </dd>

        </dl>
        <a href="@Url.Action("Index", null, new { area = string.Empty, controller = "WorkoutLogs"}, Request.Url.Scheme)" class="hvr-buzz-out">Edit</a>
    </div>*@