FitnessGuru/Models/DailyLog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FitnessGuru.Models
{
    public class DailyLog
    {
        public int Id { get; set; }
        public Guid UserId { get; set; }
        [Required]
        [Display(Name = "When did you eat?")]
        public int TimeId { get; set; }
        [ForeignKey("TimeId")]
        public virtual TimePeriod Period { get; set; }
        [Required]
        [Display(Name = "What did you eat?")]
        public int FoodId { get; set; }
        [ForeignKey("FoodId")]
        public virtual FoodModel Food { get; set; }
        [Required]
        [Display(Name = "How much did you eat?")]
        public float Quantity { get; set; }
        public float? TotalCarbohydrate { get; set; }
        public float? TotalFat { get; set; }
        public float? TotalProtein { get; set; }
        public double Calorie { get; set; }
        public DateTime TimeStamp { get; set; }
        
    }

    
}

FitnessGuru/Controllers/DailyLogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessGuru.Models;
using Microsoft.AspNet.Identity;

namespace FitnessGuru.Controllers
{
    public class DailyLogsController : Controller
    {
        private FitnessDbCM db = new FitnessDbCM();

        // GET: DailyLogs
        public ActionResult Index()
        {
            DateTime Time = DateTime.Now.Date;
            var dailyLogs = db.DailyLogs.Where(p=>p.TimeStamp==Time).Include(d => d.Food).Include(d => d.Period);
            var x = dailyLogs;
            return View(dailyLogs.ToList());
        }

        // GET: DailyLogs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyLog dailyLog = db.DailyLogs.Find(id);
            if (dailyLog == null)
            {
                return HttpNotFound();
            }
            return View(dailyLog);
        }

        // GET: DailyLogs/Create
        public ActionResult Create()
        {
            DailyLog model = new DailyLog() { UserId=GetCurrentUserId() }; 
           //ViewBag.UserId = GetCurrentUserId();
            ViewData["FoodList"] = db.Foods.Select(p => new SelectListItem() { Text = p.FoodName, Value = p.Id.ToString() }).AsEnumerable();
            ViewData["TimeList"] = db.Periods.Select(p => new SelectListItem() { Text = p.PeriodName, Value = p.TimeId.ToString() }).AsEnumerable();
            return PartialView(model);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        //add food
        public ActionResult Create([Bind(Include = "Id,UserId,TimeId,FoodId,Quantity,Calorie")] DailyLog dailyLog)
        {
            var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x =>new { x.Key, x.Value.Errors }).ToArray();
            
        
            if (ModelState.IsValid)
            {
                dailyLog.UserId = GetCurrentUserId();
                dailyLog.Calorie = GetCalorie(dailyLog);
                dailyLog.TotalCarbohydrate = GetCarbs(dailyLog);
                dailyLog.TotalFat = GetFat(dailyLog);
                dailyLog.TotalProtein = GetProtein(dailyLog);
                dailyLog.TimeStamp = DateTime.Now.Date; 
                db.DailyLogs.Add(dailyLog);
                db.SaveChanges();
                return RedirectToAction("RemainingCal", "RemainingCalories",dailyLog);
            }
            ViewBag.UserId = GetCurrentUserId();
            ViewData["FoodList"] = db.Foods.Select(p => new SelectListItem() { Text = p.FoodName, Value = p.Id.ToString() }).AsEnumerable();
            ViewData["TimeList"] = db.Periods.Select(p => new SelectListItem() { Text = p.PeriodName, Value = p.TimeId.ToString() }).AsEnumerable();
            return View(dailyLog);
        }

        // GET: DailyLogs/Edit/5
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    DailyLog dailyLog = db.DailyLogs.Find(id);
        //    if (dailyLog == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.FoodId = new SelectList(db.Foods, "Id", "FoodName", dailyLog.FoodId);
        //    ViewBag.TimeId = new SelectList(db.Periods, "TimeId", "PeriodName", dailyLog.TimeId);
        //    return View(dailyLog);
        //}

        // POST: DailyLogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,UserId,TimeId,FoodId,Quantity,Calorie")] DailyLog dailyLog)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(dailyLog).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.FoodId = new SelectList(db.Foods, "Id", "FoodName", dailyLog.FoodId);
        //    ViewBag.TimeId = new SelectList(db.Periods, "TimeId", "PeriodName", dailyLog.TimeId);
        //    return View(dailyLog);
        //}

        // GET: DailyLogs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DailyLog dailyLog = db.DailyLogs.Find(id);
            if (dailyLog == null)
            {
                return HttpNotFound();
            }
            return View(dailyLog);
        }

        // POST: DailyLogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DailyLog dailyLog = db.DailyLogs.Find(id);
            db.DailyLogs.Remove(dailyLog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public Guid GetCurrentUserId()
        { //to allow user to view only their details
            return new Guid(User.Identity.GetUserId());
        }
        public bool EnsureIsUserContact(UserInfo userInfo)
        {
            return userInfo.UserId == GetCurrentUserId();
        }

        public float GetCalorie(DailyLog dailyLog)
        {

            // food = from Foods in FoodModel where food.Id == dailyLog.FoodId;
            //food = db.Foods.Where(p => p.Id.Equals(db.DailyLogs.FoodId));
            //var results = from f in FoodModel
            //              where f.Id<int>("Id") == dailyLog.FoodId
            //              select f;
           // var uerId = new Guid(User.Identity.GetUserId());
            var food = db.Foods.Find(dailyLog.FoodId);
            // var res = db.DailyLogs.Where(p => p.FoodId == dailyLog.FoodId && p.UserId == uerId).ToList(); 
            float calorie = dailyLog.Quantity * food.Calories;
            return calorie;
        }
        public float GetCarbs(DailyLog dailyLog)
        {

             var food = db.Foods.Find(dailyLog.FoodId);
            float carbs = dailyLog.Quantity * food.Carbohydrate;

            return carbs;
        }
        public float GetFat(DailyLog dailyLog)
        {

            var food = db.Foods.Find(dailyLog.FoodId);
            float fat = dailyLog.Quantity * food.Fat;

            return fat;
        }
        public float GetProtein(DailyLog dailyLog)
        {

            var food = db.Foods.Find(dailyLog.FoodId);
            float protein = dailyLog.Quantity * food.Protein;

            return protein;
        }

    }
}

FitnessGuru/Views/DailyLogs/Create.cshtml
@model FitnessGuru.Models.DailyLog

@{
    ViewBag.Title = "Create";

}


@using (Html.BeginForm("Create", "DailyLogs", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>DailyLog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId)

                @*@Html.EditorFor(model => model.UserId, new { id = "UserId", value = ViewBag.UserId })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeId, "TimeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TimeId", ViewData["TimeList"] as IEnumerable<SelectListItem>, "Select One", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TimeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId, "FoodId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FoodId", ViewData["FoodList"] as IEnumerable<SelectListItem>, "Add a Food", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>


        <div id="crtbutton" class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>


    </div>
}

FitnessGuru/Views/DailyLogs/Delete.cshtml
@model FitnessGuru.Models.DailyLog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DailyLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Food.FoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Food.FoodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period.PeriodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period.PeriodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calorie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FitnessGuru/Views/DailyLogs/Details.cshtml
@model FitnessGuru.Models.DailyLog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DailyLog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Food.FoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Food.FoodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Period.PeriodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Period.PeriodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Calorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Calorie)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FitnessGuru/Views/DailyLogs/Edit.cshtml
@model FitnessGuru.Models.DailyLog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DailyLog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TimeId, "TimeId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TimeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TimeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodId, "FoodId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FoodId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FoodId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Calorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Calorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Calorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FitnessGuru/Views/DailyLogs/Index.cshtml
@model IEnumerable<FitnessGuru.Models.DailyLog>

@{
    ViewBag.Title = "Food You Ate Today!!";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


    <h2>@ViewBag.Title</h2>

    ADD A FOOD
    <button type="button" class="btn btn" id="addFood"> <i class="fa fa-plus fa-spin fa-lg fa-fw" aria-hidden="true"></i></button>


    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Food.FoodName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Period.PeriodName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Calorie)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Food.FoodName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Period.PeriodName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Calorie)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>





@section Scripts {
    <script>

        $("#addFood").on('click', function () {

            $.ajax({
                url: '/DailyLogs/Create',
                type: 'get'
            }).done(function (data) {
                $("#modalBody").html(data);
                $("#myModalLabel").html("Add Food");
                $("#myModal").modal("show");
            }).fail(function (err) {
                alert(err);
            });

        });

    </script>
}