FitnessGuru/Controllers/ForaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessGuru.Models;
using Microsoft.AspNet.Identity;

namespace FitnessGuru.Controllers
{
    public class ForaController : Controller
    {
        private FitnessDbCM db = new FitnessDbCM();

        // GET: Fora
        public ActionResult Index()
        {
            return View(db.Forums.ToList());
        }

        public ActionResult QuesAns()
        {
            return View(db.Forums.ToList());
        }
        public ActionResult portletPartial(Models.Forum model)
        {
            return PartialView(model);
        }

        // GET: Fora/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Forum forum = db.Forums.Find(id);
            if (forum == null)
            {
                return HttpNotFound();
            }
            return View(forum);
        }

        // GET: Fora/Create
        public ActionResult Create()
        {
            Forum forum= new Forum();
            forum.UserId = GetCurrentUserId();
            var userInfo = db.Users.Where(p => p.UserId == forum.UserId).FirstOrDefault();
            forum.UserName = userInfo.FName + " " + userInfo.LName;
            forum.TimeofPost = DateTime.Now;

            return PartialView(forum);
        }

        // POST: Fora/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserId,Content,TimeofPost,ReplyId")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                forum.UserId = GetCurrentUserId();
                forum.TimeofPost = DateTime.Now;
                db.Forums.Add(forum);
                db.SaveChanges();
                return RedirectToAction("QuesAns");
            }

            return View(forum);
        }



        public ActionResult Reply(int? id)
        {
            Forum model = new Forum() { UserId = GetCurrentUserId() };
            model.ReplyId = id;
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reply(Forum forum)
        {
            if (ModelState.IsValid)
            {
                forum.UserId = GetCurrentUserId();
                forum.TimeofPost = DateTime.Now;
                db.Forums.Add(forum);
                db.SaveChanges();
                return RedirectToAction("QuesAns");
            }

            return View(forum);
        }


        // GET: Fora/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Forum forum = db.Forums.Find(id);
            if (forum == null)
            {
                return HttpNotFound();
            }
            return View(forum);
        }

        // POST: Fora/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserId,Content,TimeofPost,ReplyId")] Forum forum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(forum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("QuesAns");
            }
            return View(forum);
        }

        // GET: Fora/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Forum forum = db.Forums.Find(id);
            if (forum == null)
            {
                return HttpNotFound();
            }
            return View(forum);
        }

        // POST: Fora/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Forum forum = db.Forums.Find(id);
            db.Forums.Remove(forum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public Guid GetCurrentUserId()
        { //to allow user to view only their details
            return new Guid(User.Identity.GetUserId());
        }
        public bool EnsureIsUserContact(UserInfo userInfo)
        {
            return userInfo.UserId == GetCurrentUserId();
        }
    }
}

FitnessGuru/Views/Fora/Create.cshtml
@model FitnessGuru.Models.Forum

@{
    ViewBag.Title = "Create";
    Layout = null;
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Fora", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Forum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId)
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.TimeofPost)
            </div>
        </div>
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">

        <div class="col-md-10">
            @Html.HiddenFor(model => model.ReplyId)
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" >
            <input type="submit"id="createComment" value="Create" class="btn btn-default" />
        </div>
    </div>
    </div>
}


@section Scripts {
    <script>
    $("#createComment").on('click', function () {
        //var model = { 'id': Id, 'comments': comments };
        var comments = $('#txtComments').val();
        

        $.ajax({
            //your params as it is
            url: '/comments1/SaveComments',
            data: { 'commenty': comments },
              type: 'post'
        }).done(function (response) {
            //window.location = redirectURl //for redirecting to article details page
            //if you are passing id as parameter to the redirected page then you can do something like this.
          // window.location = response.redirectUrl + '/' + response.Id;
            // window.location.href = 'Url.Action("details", "articles", new { id = "id1" })';

           $.ajax({
               url: '/comments1/Index?Id=' + response.Id,
               type:'GET'
           }).done(function(responsecomment) {
               $('#commentsection').html(responsecomment);
           }).fail(function(err) {
               alert("Error Occured : " + err);
           });
        }).fail(function (error) {

        });

        });
    </script>
}

FitnessGuru/Views/Fora/Delete.cshtml
@model FitnessGuru.Models.Forum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Forum</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TimeofPost)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TimeofPost)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ReplyId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ReplyId)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

FitnessGuru/Views/Fora/Details.cshtml
@model FitnessGuru.Models.Forum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Forum</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.UserId)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TimeofPost)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TimeofPost)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ReplyId)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ReplyId)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

FitnessGuru/Views/Fora/Edit.cshtml
@model FitnessGuru.Models.Forum

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Forum</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.TimeofPost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TimeofPost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TimeofPost, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ReplyId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReplyId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReplyId, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "QueAns")
    </div>
</body>
</html>

FitnessGuru/Views/Fora/Index.cshtml
@{
    ViewBag.Title = "Food You Ate Today!!";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
@*@model IEnumerable<FitnessGuru.Models.Forum>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TimeofPost)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeofPost)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
                @Html.ActionLink("Reply", "Reply", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<p>
    <div class="input-group">
        <span class="input-group-addon">Comment here</span>
        <input type="text" id="txtComments" class="form-control" placeholder="text" aria-describedby="basic-addon1">
    </div>
    <button type="button" class="btn btn-primary" id="createComment">Comment</button>
</p>
<div id="commentsection">
    @Html.Action("Index", "comments1", Model.id);
</div>*@


@Html.Action("QuesAns", "Fora")

FitnessGuru/Views/Fora/QuesAns.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<FitnessGuru.Models.Forum>

@{
    ViewBag.Title = "QuesAns";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@*<h2>QuesAns</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimeofPost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReplyId)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimeofPost)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReplyId)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }

    </table>*@



@foreach (var item in Model)
{
    if (item.ReplyId==null)
    {


    <div class="portlet-grid-page">
        <div class="portlet-grid panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">@item.UserName</h3>
            </div>
            <div class="panel-body">

                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Content)
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
                        @Html.ActionLink("Reply", "Reply", new { id = item.Id })
                    </td>
                </tr>

            </div>
        </div>
    </div>
    }

}
<i class="fa fa-comment" id = "addComment"aria-hidden="true">Comment</i>

@section Scripts {
    <script>

        $("#addComment").on('click', function () {

            $.ajax({
                url: '/Fora/Create',
                type: 'get'
            }).done(function (data) {
                $("#modalBody").html(data);
                $("#myModalLabel").html("Add Food");
                $("#myModal").modal("show");
            }).fail(function (err) {
                alert(err);
            });

        });

    </script>
}

FitnessGuru/Views/Fora/Reply.cshtml
@model FitnessGuru.Models.Forum

@{
    ViewBag.Title = "Reply";
}

<h2>Reply</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Forum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">

            <div class="col-md-10">
                @Html.HiddenFor(model => model.ReplyId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Reply" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>